## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-cassandra-exporter
  name: test-cassandra-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cassandra-exporter
  template:
    metadata:
      labels:
        app: test-cassandra-exporter
    spec:
      containers:
      - image: bitnami/cassandra-exporter
        name: cassandra-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-cassandra-exporter
  name: test-cassandra-exporter
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-cassandra-exporter
  sessionAffinity: None
  type: ClusterIP
